### ISSUE TITLE
Kunne godt bruge lidt hjælp her

### ISSUE THREAD

**Issue by MadsRossen** [MadsRossen/p1ex#6]
Hvordan får jeg den her til at subscribe til navi/navigation.cpp filen? 

https://github.com/MadsRossen/p1ex/blob/3f905ad9322159ab29edf355d91b1118ce87701c/src/map.cpp#L27

**Comment by kajMork** [comment]
Din main funktion er ikke i noget loop. koden bliver kun kørt igennem én gang.
Jeg kan ikke se nogen fejl i opsætning af subscriberne, men for at dine subscriber skal kunne modtage beskeder skal de køre i et loop med ros.spin() eller ros.spinOnce()

**Comment by kajMork** [comment]
Derudover prøver du også at anvende din subscriber som en værdi, f.eks. her:
https://github.com/MadsRossen/p1ex/blob/3f905ad9322159ab29edf355d91b1118ce87701c/src/map.cpp#L36
Det kan man ikke. I stedet skal du omskrive din list funktion så du kan retunere en passende variabel. Du skal dermed også huske at "call" din list funktion i din main funktion, ellers udebliver den fra loopet og kører dermed kun én gang.
https://github.com/MadsRossen/p1ex/blob/3f905ad9322159ab29edf355d91b1118ce87701c/src/map.cpp#L12
