### ISSUE TITLE
Og modsat med det her:

### ISSUE THREAD

**Issue by MadsRossen** [MadsRossen/p1ex#7]
Hvordan får jeg det her til at publish tallene til den anden node? Tror jeg har gjort det helt forkert...

https://github.com/MadsRossen/p1ex/blob/3f905ad9322159ab29edf355d91b1118ce87701c/src/navigation.cpp#L31-L35

**Comment by kajMork** [comment]
I din stringstream "msglen" indsætter du 3 variabler: "width", "length",  og "count".
https://github.com/MadsRossen/p1ex/blob/3f905ad9322159ab29edf355d91b1118ce87701c/src/navigation.cpp#L33
count er en variabel du ikke har defineret og komma er ikke måden man opdeler variabler på i en stringstream, der anvender man "<<".

**Comment by kajMork** [comment]
Og som i map.cpp kører din main funktion ikke i et loop med ros.spin() eller ros.spinOnce() og derfor vil din "msg" kun blive sendt èn gang i og med at main funktionen kun kører én gang.
